node('maven') 
{
  stage ('buildDev')
  {  
    openshiftBuild(namespace: 'dev-web', buildConfig: 'country-web', showBuildLogs: 'true')
  }
  
  stage ('deployDev')
  {
    openshiftDeploy(namespace: 'dev-web', deploymentConfig: 'country-web')
    openshiftScale(namespace: 'dev-web', deploymentConfig: 'country-web',replicaCount: '1')
    openshiftTag(namespace: 'dev-web',destinationNamespace: 'dev-web', destStream: 'country-web', destTag: 'test', srcStream: 'country-web', srcTag: 'latest')
    openshiftScale(namespace: 'dev-web', deploymentConfig: 'country-web',replicaCount: '0')
  }
  
  stage ('deployTest')
  {
    openshiftDeploy(namespace: 'test', deploymentConfig: 'country-web')
    openshiftScale(namespace: 'test', deploymentConfig: 'country-web',replicaCount: '1')
    openshiftTag(namespace: 'dev-web', destinationNamespace: 'dev-web', destStream: 'country-web', destTag: 'prod', srcStream: 'country-web', srcTag: 'test')
    openshiftScale(namespace: 'dev-web', deploymentConfig: 'country-web',replicaCount: '0')
  }
  
  stage ('approval')
  {
    timeout(time: 1, unit: 'HOURS') { input id: 'AppProd', message: 'Approve deployment to Production?', ok: 'OK', submitter: 'benemon'}
  }
  
  stage ('deployProd')
  {
    openshiftDeploy(namespace: 'prod', deploymentConfig: 'country-web')
    openshiftScale(namespace: 'prod', deploymentConfig: 'country-web',replicaCount: '1')
  }
}
